### ISSUE TITLE
Error in npm run dev

### ISSUE THREAD

**Issue by chaitjo** [datagovsg/school-picker#2]
Upon running `npm run dev`, the following error showed up and I was not able to run the app in localhost:9000.
```
chait@chait:~/school-picker$ npm run dev

> datagovsg-school-picker@1.0.0 dev /home/chait/school-picker
> npm run watch-server & npm run dev-server


> datagovsg-school-picker@1.0.0 dev-server /home/chait/school-picker
> webpack-dev-server --config ./webpack.config.js --colors --progress


> datagovsg-school-picker@1.0.0 watch-server /home/chait/school-picker
> babel-watch src/server.js

/home/chait/school-picker/src/server.js:1
(function (exports, require, module, __filename, __dirname) { import _Object$assign from 'babel-runtime/core-js/object/assign';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at babelWatchLoader (/home/chait/school-picker/node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/home/chait/school-picker/node_modules/babel-watch/runner.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at process.on (/home/chait/school-picker/node_modules/babel-watch/runner.js:108:21)
 10% building modules 0/1 modules 1 active ... ./src/style/base.styl ./src/index 10% building modules 1/1 modules 0 active
Project is running at http://localhost:9000/
webpack output is served from /
Content not from webpack is served from /home/chait/school-picker/public
404s will fallback to /index.html
 10% building modules 1/2 modules 1 active ...client/index.js?http://localhost:9 10% building modules 1/3 modules 2 active ...ode_modules/webpack/hot/dev-server 10% building modules 1/4 modules 3 active ...odules/webpack/hot/only-dev-server 10% building modules 2/4 modules 2 active ...odules/webpack/hot/only-dev-server 10% building modules 3/4 modules 1 active ...odules/webpack/hot/only-dev-server 10% building modules 4/5 modules 1 active .../webpack/hot nonrecursive /^\.\/lo 10% building modules 4/6 modules 2 active ...s/webpack-dev-server/client/socket 10% building modules 4/7 modules 3 active .../webpack-dev-server/client/overlay 10% building modules 4/8 modules 4 active ...r/node_modules/webpack/hot/emitter 10% building modules 4/9 modules 5 active ...home/chait/school-picker/src/index 10% building modules 5/9 modules 4 active ...home/chait/school-picker/src/index 10% building modules 5/10 modules 5 active ...school-picker/node_modules/url/ur 10% building modules 5/11 modules 6 active ...ait/school-picker/src/style/base. 10% building modules 6/11 modules 5 active ...school-picker/node_modules/url/ur 10% building modules 6/12 modules 6 active ...dules/webpack/hot/log-apply-resul 10% building modules 6/13 modules 7 active ...ait/school-picker/src/style/base. 10% building modules 7/13 modules 6 active ...ait/school-picker/src/style/base. 10% building modules 8/13 modules 5 active ...ait/school-picker/src/style/base. 11% building modules 9/13 modules 4 active ...ait/school-picker/src/style/base. 11% building modules 10/13 modules 3 active ...ait/school-picker/src/style/base 11% building modules 11/13 modules 2 active ...ait/school-picker/src/style/base 11% building modules 12/13 modules 1 active ...ait/school-picker/src/style/base 11% building modules 12/14 modules 2 active ...e-style-loader/lib/addStylesClie 11% building modules 12/15 modules 3 active ...ome/chait/school-picker/src/rout 11% building modules 13/15 modules 2 active ...ome/chait/school-picker/src/rout 11% building modules 13/16 modules 3 active ...chool-picker/node_modules/url/ut 11% building modules 13/17 modules 4 active ...-picker/node_modules/events/even 11% building modules 14/17 modules 3 active ...-picker/node_modules/events/even 11% building modules 14/18 modules 4 active ...cker/node_modules/strip-ansi/ind
.
.
.
 69% building modules 975/977 modules 2 active ...library/modules/_to-absolute-i 69% building modules 976/977 modules 1 active ...library/modules/_to-absolute-i 69% building modules 977/978 modules 1 active ...es/core-js/library/modules/_in 69% building modules 978/979 modules 1 active ...ait/school-picker/src/style/baHash: eb606bc3353f01be4077                    
Version: webpack 2.7.0
Time: 12973ms
     Asset    Size  Chunks                    Chunk Names
 bundle.js  6.6 MB       0  [emitted]  [big]  main
bundle.css  260 kB       0  [emitted]  [big]  main
webpack: Compiled successfully.
[HPM] Error occurred while trying to proxy request / from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
I have to press Ctrl+C at this point to stop the server.

How do I solve this issue?

Note: I am using Ubuntu 16.04. Here is the output from `npm install`:
```
chait@chait:~/school-picker$ npm install
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@3.13.1 install /home/chait/school-picker/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-48_binding.node
Download complete  ] - :
Binary saved to /home/chait/school-picker/node_modules/node-sass/vendor/linux-x64-48/binding.node
Caching binary to /home/chait/.npm/node-sass/3.13.1/linux-x64-48_binding.node

> node-sass@3.13.1 postinstall /home/chait/school-picker/node_modules/node-sass
> node scripts/build.js

Binary found at /home/chait/school-picker/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
datagovsg-school-picker@1.0.0 /home/chait/school-picker
├── @mapbox/geojson-normalize@0.0.1 
├── @mapbox/polyline@0.2.0 
├── @turf/buffer@3.14.0 
├── @turf/combine@3.14.0 
├── @turf/helpers@3.13.0 
├── @turf/meta@3.14.0 
.
.
.
├─┬ yargs@7.1.0 
│ └── camelcase@3.0.0 
└─┬ yargs-parser@5.0.0 
  └── camelcase@3.0.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by chaitjo** [comment]
I am able to run the production version as intended, by the way. If I am making changes to certain aspects of the application, do I need to run the development version as such, or is running the production version to see the changes enough?

**Comment by yongjun21** [comment]
Sorry, it was a bug from an earlier commit. I have pushed another [commit](https://github.com/datagovsg/school-picker/commit/a36f88332bc2d9b1a3a38e54e41ebb1d90507599) to fix it.
